# Generated by Django 4.2.3 on 2023-07-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
